# Generated by Django 5.0.3 on 2024-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDb',
            fields=[
                ('row_number', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('product_price', models.TextField(blank=True, null=True)),
                ('product_company', models.TextField(blank=True, null=True)),
                ('inn', models.BigIntegerField(blank=True, null=True)),
                ('ogrn', models.BigIntegerField(blank=True, null=True)),
                ('okpd2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
